# Generated by Django 5.0.6 on 2024-06-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_stat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatistics',
        ),
    ]
